### ISSUE TITLE
Ukraine is missing Crimea

### ISSUE THREAD

**Issue by nealmcb** [TyVik/geopuzzle#823]
When I played the world puzzle yesterday, the borders for Ukraine did not include Crimea.
Of course, other governments and international bodies have not recognized Russia's illegal annexation of Crimea.

I though you used openstreetmap data, and they still include Crimea in Ukraine: [Relation: ‪Ukraine‬ \(‪60199‬\) \| OpenStreetMap](https://www.openstreetmap.org/relation/60199#map=6/48.451/31.179).

Perhaps it's related to your exclusion of Russia (and the US and Canada and ??) from the map entirely, and the fact that OSM also acknowledges Russia's claim ([Relation: ‪Russia‬ \(‪60189‬\) \| OpenStreetMap](https://www.openstreetmap.org/relation/60189#map=7/46.698/34.718))? But surely you should resolve this conflict in favor of the country outline which players are playing with around, and the territorial boundary as nearly universally recognized.

Please fix this.
And thanks for a marvelous set of games!

**Comment by TyVik** [comment]
I've exclude Russia, Canada and US as too large countries (that have a lot of points). Please, pay attention on Chile and Norway - they have the same issue, but I can reduce shapes (sacrifice islands). Unfortunately, it's not working with first three.

Crimea is the part of Russia from my point of view, as you can find by Russia Relation at OSM. 
Our world has a lot of conflict territories: West Sahara, Falkland Islands, South Sudan, Cyprus, Somalia, Kosovo, Kashmir, Taiwan... Why you pay attention only on Crimea? Just because it is more promoted? I can find a boarder point at north of the peninsula, not east.

> But surely you should resolve this conflict in favor of the country outline which players are playing with around, and the territorial boundary as nearly universally recognized.

Ha-ha, GeoLite blocks my account, so I cannot decode location by IP for free. Moreover, PayPal and Visa blocked me, so I cannot even pay for my hosting and must spent my time for migration.
